version: '3.2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "30306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=azkaban
      - MYSQL_USER=azkaban
      - MYSQL_PASSWORD=azkaban
      - MYSQL_DATABASE=azkaban
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
  azkban-executor:
    build: ./azkaban-executor/
    image: azkaban-executor:latest
    depends_on:
      - mysql
    ports:
      - "12321"
    volumes:
      - ./azkaban-executor.properties:/opt/azkaban-exec-server/conf/azkaban.properties
  azkaban-web:
    build: ./azkaban-web
    image: azkaban-web:latest
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=azkaban
    ports:
      - "8443:8443"
    volumes:
      - ./azkaban-web-server.properties:/opt/azkaban-web-server/conf/azkaban.properties
