apiVersion: v1
kind: Service
metadata:
  name: azkaban-web-service
  labels:
    app: azkaban
spec:
  ports:
    - port: 8443
      nodePort: 30443
  selector:
    app: azkaban
    tier: web
  type: "NodePort"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azkaban-web-deployment
  labels:
    app: azkaban
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azkaban
        tier: web
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: jorizci/azkaban-web:latest
        name: azkaban-web
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: azkaban-web
        volumeMounts:
        - mountPath: /opt/azkaban-web-server/conf/azkaban.properties
          name: azkaban-config
          subPath: azkaban.properties
      volumes:
      - name: azkaban-config
        configMap:
          name: azkaban-web-server.properties
          items:
          - key: azkaban-web-server.properties
            path: azkaban.properties
