apiVersion: v1
kind: Service
metadata:
  name: azkaban-mysql-service
  labels:
    app: azkaban
spec:
  ports:
    - port: 3306
      nodePort: 30306
  selector:
    app: azkaban
    tier: mysql
  type: "NodePort"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azkaban-mysql-deployment
  labels:
    app: azkaban
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azkaban
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: azkaban
         - name: MYSQL_USER
           value: azkaban
         - name: MYSQL_PASSWORD
           value: azkaban
         - name: MYSQL_DATABASE
           value: azkaban
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
#        - name: MYSQL_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-pass
#              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: azkaban-database
          subPath: mysql
      volumes:
      - name: azkaban-database
        persistentVolumeClaim:
          claimName: nfs-azkaban-db-pvc
